Added error logging
Will now provide output on /tmp/drauger-installer/log.txt as to why drauger-installer exits without installing a *.deb file.

diff --git a/bin/drauger-installer b/bin/drauger-installer
--- a/bin/drauger-installer
+++ b/bin/drauger-installer
@@ -20,7 +20,7 @@
 #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #  MA 02110-1301, USA.
 #
-version="0.3.0"
+version="0.3.1"
 if [ "$1" == "--version" ]; then
 	/bin/echo -e "\ndrauger-installer version $version\n"
 	exit 0
@@ -34,6 +34,7 @@ if $(/bin/echo "$1" | /bin/grep -q '.deb') && $(/bin/echo "$1" | /bin/grep -q '/
 	ver=$(/usr/bin/dpkg-deb -f $1 Version)
 	if [ "$(/usr/bin/dpkg -s $pak 2>/dev/null | /bin/grep 'Version: ' | /bin/sed 's/Version: //g')" == "$ver" ]; then
 		/bin/echo "This version of $pak is already installed."
+		/etc/drauger-installer/log-out.sh 1 /bin/drauger-installer "/bin/drauger-installer detected provided *.deb package was already installed."
 		exit 1
 	fi
 	des=$(/usr/bin/dpkg-deb -f "$1" Description)
@@ -95,8 +96,12 @@ Would you like to $action this package? [y/N]: " ans
 			/usr/bin/sudo /usr/bin/apt -y install "$1" && /bin/echo -e "\n$pak has been $actioned\n"
 		} && {
 			exit 0
-		} || exit 2
+		} || {
+			/etc/drauger-installer/log-out.sh 2 /bin/drauger-installer "Installation of provided *.deb package $1 failed."
+			exit 2
+		}
 	else
+		/etc/drauger-installer/log-out.sh 1 /bin/drauger-installer "Installation Canceled"
 		exit 1
 	fi
 elif $(/bin/echo "$1" | /bin/grep -q '.deb'); then
@@ -104,6 +109,7 @@ elif $(/bin/echo "$1" | /bin/grep -q '.deb'); then
 	ver=$(/usr/bin/dpkg-deb -f "$1" Version)
 	if [ "$(/usr/bin/dpkg -s $pak 2>/dev/null | /bin/grep 'Version: ' | /bin/sed 's/Version: //g')" == "$ver" ]; then
 		/bin/echo "This version of $pak is already installed."
+		/etc/drauger-installer/log-out.sh 1 /bin/drauger-installer "/bin/drauger-installer detected provided *.deb package was already installed."
 		exit 1
 	fi
 	des=$(/usr/bin/dpkg-deb -f "$1" Description)
@@ -164,8 +170,12 @@ Would you like to $action this package? [y/N]: " ans
 			/usr/bin/sudo /usr/bin/apt -y install ./"$1" && /bin/echo -e "\n$pak has been $actioned\n"
 		} && {
 			exit 0
-		} || exit 2
+		} || {
+			/etc/drauger-installer/log-out.sh 2 /bin/drauger-installer "Installation of provided *.deb package $1 failed."
+			exit 2
+		}
 	else
+		/etc/drauger-installer/log-out.sh 1 /bin/drauger-installer "Installation Canceled"
 		exit 1
 	fi
 fi
