bug fix
apps that are large or require multiple dependencies to be installed before hand require the user to confirm they want to install said app. This has been disabled so as to speed up install and fix install crashes through the GUI.

diff --git a/drauger-installer b/drauger-installer
--- a/drauger-installer
+++ b/drauger-installer
@@ -20,7 +20,7 @@
 #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 #  MA 02110-1301, USA.
 #
-version="0.1.0"
+version="0.1.1"
 if [ "$1" == "--version" ]; then
 	echo -e "\ndrauger-installer version $version\n"
 	exit 0
@@ -46,7 +46,7 @@ Description: $des
 	read -p "$info Would you like to install this package? [y/N]: " ans
 	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
 		{ 
-			sudo apt install "$1" && echo -e "\n$pak has been installed\n"
+			sudo apt -y install "$1" && echo -e "\n$pak has been installed\n"
 		} && {
 			exit 0
 		} || exit 2
@@ -70,7 +70,7 @@ Description: $des
 	read -p "$info Would you like to install this package? [y/N]: " ans
 	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
 		{ 
-			sudo apt install ./"$1" && echo -e "\n$pak has been installed\n"
+			sudo apt -y install ./"$1" && echo -e "\n$pak has been installed\n"
 		} && {
 			exit 0
 		} || exit 2
@@ -100,7 +100,7 @@ fi
 zenity --question --no-wrap --text="Package Info:\n\n$info\n\nWould you like to install this package?"
 x="$?"
 if [ "$x" == "0" ]; then
-	( pkexec apt install "$install" | zenity --progress --pulsate --auto-close --no-cancel --text="Installing $pak . . ." && notify-send "$pak has been installed" ) || zenity --error --no-wrap --text="An error was encountered installing your app. Error code $? was thrown from apt."
+	( pkexec apt -y install "$install" | zenity --progress --pulsate --auto-close --no-cancel --text="Installing $pak . . ." && notify-send "$pak has been installed" ) || zenity --error --no-wrap --text="An error was encountered installing your app. Error code $? was thrown from apt."
 else
 	exit 1
 fi
