contextual output corrections

diff --git a/drauger-installer b/drauger-installer
--- a/drauger-installer
+++ b/drauger-installer
@@ -113,14 +113,16 @@ fi
 if $(dpkg -l "$pak" | grep -q "$pak"); then
 		action="update"
 		actioned="updated"
+		actioning="Updating"
 	else
 		action="install"
 		actioned="installed"
+		actioning="Installing"
 	fi
 zenity --question --no-wrap --text="Package Info:\n\n$info\n\nWould you like to $action this package?"
 x="$?"
 if [ "$x" == "0" ]; then
-	( pkexec apt -y install "$install" | zenity --progress --pulsate --auto-close --no-cancel --text="Installing $pak . . ." && notify-send "$pak has been $actioned" ) || zenity --error --no-wrap --text="An error was encountered installing your app. Error code $? was thrown from apt."
+	( pkexec apt -y install "$install" | zenity --progress --pulsate --auto-close --no-cancel --text="$actioning $pak . . ." && notify-send "$pak has been $actioned" ) || zenity --error --no-wrap --text="An error was encountered $actioning your app. Error code $? was thrown from apt."
 else
 	exit 1
 fi
